import { Component } from '@angular/core';

@Component({
  selector: 'app-main',
  templateUrl: './main.component.html',
  styleUrls: ['./main.component.scss'],
})
export class MainComponent {
  productArray = [
    {
      name: 'David N',
      distance: '4 kms from Brisbane City, QLD',
      location: 'Location 1',
      rating: '4.4',
      quality: ['Licensed', 'ABN'],
      metaData: true,
      tags: [
        'Architectural Homes',
        'Commercial',
        'Garages',
        'Civil works management',
      ],
      imgPath: 'assets/person1.png',
    },
    {
      name: 'Omar D',
      distance: '4 kms from Brisbane City, QLD',
      location: 'Location 1',
      rating: '',
      quality: ['Licensed', 'ABN'],
      metaData: true,
      tags: [
        'Architectural Homes',
        'Commercial',
        'Garages',
        'Civil works management',
      ],
      imgPath: 'assets/person2.png',
    },
    {
      name: 'Jacob J',
      distance: 10,
      location: '4 kms from New York, USA',
      rating: '4.4',
      quality: ['Licensed', 'ABN'],
      metaData: true,
      tags: [
        'Architectural Homes',
        'Commercial',
        'Garages',
        'Civil works management',
      ],
      imgPath: 'assets/person3.png',
    },
    {
      name: 'Omar D',
      distance: '4 kms from Brisbane City, QLD',
      location: 'Location 1',
      rating: '',
      quality: ['Licensed', 'ABN'],
      metaData: true,
      tags: [
        'Architectural Homes',
        'Commercial',
        'Garages',
        'Civil works management',
      ],
      imgPath: 'assets/person1.png',
    },
    {
      name: 'Jacob J',
      distance: '4 kms from Brisbane City, QLD',
      location: 'Location 1',
      rating: '4.4',
      quality: ['Licensed', 'ABN'],
      metaData: true,
      tags: [
        'Architectural Homes',
        'Commercial',
        'Garages',
        'Civil works management',
      ],
      imgPath: 'assets/person2.png',
    },
    {
      name: 'Jacob J',
      distance: '4 kms from Brisbane City, QLD',
      location: 'Location 1',
      rating: '4.4',
      quality: ['Licensed', 'ABN'],
      metaData: true,
      tags: [
        'Architectural Homes',
        'Commercial',
        'Garages',
        'Civil works management',
      ],
      imgPath: 'assets/person3.png',
    },
    {
      name: 'Mike',
      distance: '4 kms from Brisbane City, QLD',
      location: 'Location 1',
      rating: '4.4',
      quality: ['Licensed', 'ABN'],
      metaData: true,
      tags: [
        'Architectural Homes',
        'Commercial',
        'Garages',
        'Civil works management',
      ],
      imgPath: 'assets/person1.png',
    },
    {
      name: 'Omar D',
      distance: '4 kms from Brisbane City, QLD',
      location: 'Location 1',
      rating: '4.4',
      quality: ['Licensed', 'ABN'],
      metaData: true,
      tags: [
        'Architectural Homes',
        'Commercial',
        'Garages',
        'Civil works management',
      ],
      imgPath: 'assets/person1.png',
    },
    {
      name: 'Pulkit',
      distance: '4 kms from Brisbane City, QLD',
      location: 'Location 1',
      rating: '4.4',
      quality: ['Licensed', 'ABN'],
      metaData: true,
      tags: [
        'Architectural Homes',
        'Commercial',
        'Garages',
        'Civil works management',
      ],
      imgPath: 'assets/person3.png',
    },
  ];
}
